# Generated by Django 3.2.3 on 2022-11-16 23:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=None, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='UserShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('commune', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
