# Generated by Django 3.2.3 on 2022-11-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
