# Generated by Django 3.2.3 on 2022-11-27 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_userprofile_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
