# Generated by Django 3.2.3 on 2022-10-31 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20221027_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acountlesstransaction',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='acountlesstransaction',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requested',
        ),
        migrations.AddField(
            model_name='acountlesstransaction',
            name='payment_id',
            field=models.CharField(default=0, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acountlesstransaction',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='acountlesstransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('REQUESTED', 'requested'), ('CANCELED', 'canceled'), ('CONFIRMED', 'confirmed'), ('FAILED', 'failed')], default='CREATED', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(default=11111111, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('REQUESTED', 'requested'), ('CANCELED', 'canceled'), ('CONFIRMED', 'confirmed'), ('FAILED', 'failed')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='acountlesstransaction',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acountlesstransaction',
            name='buyer_lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acountlesstransaction',
            name='buyer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acountlesstransaction',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
