# Generated by Django 3.2.3 on 2022-11-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20221019_0228'),
        ('transactions', '0003_auto_20221031_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acountlesstransactionpointer',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acountless_transaction_pointers', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='acountlesstransactionpointer',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_pointers', to='transactions.acountlesstransaction'),
        ),
        migrations.AlterField(
            model_name='transactionpointer',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_pointers', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='transactionpointer',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_pointers', to='transactions.transaction'),
        ),
    ]
