# Generated by Django 3.2.3 on 2022-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20221102_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acountlesstransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('REQUESTED', 'requested'), ('CANCELED', 'canceled'), ('SUCCEDED', 'confirmed'), ('FAILED', 'failed')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('REQUESTED', 'requested'), ('CANCELED', 'canceled'), ('SUCCEDED', 'confirmed'), ('FAILED', 'failed')], default='CREATED', max_length=10),
        ),
    ]
