# Generated by Django 3.2.3 on 2022-11-17 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20221116_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='shipping_addresses',
            new_name='shipping_address',
        ),
    ]
