# Generated by Django 3.2.3 on 2022-11-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_shipping_addresses_transaction_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acountlesstransaction',
            name='rut',
        ),
    ]
