# Generated by Django 3.2.3 on 2022-11-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20221117_1748'),
        ('transactions', '0009_remove_acountlesstransaction_rut'),
    ]

    operations = [
    ]
