# Generated by Django 3.2.3 on 2022-11-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0010_merge_20221118_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['content_type', 'object_id'], name='transaction_content_0d9f7a_idx'),
        ),
    ]
