# Generated by Django 3.2.3 on 2022-11-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20221120_1855'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coupon',
            name='transaction_content_0d9f7a_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='object_id',
        ),
        migrations.AddField(
            model_name='acountlesstransaction',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountless_transaction', to='transactions.coupon'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='transactions.coupon'),
        ),
    ]
