# Generated by Django 3.2.3 on 2022-11-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20221124_0108'),
        ('transactions', '0012_auto_20221120_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acountlesstransactionpointer',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='transactionpointer',
            name='publication',
        ),
        migrations.AddField(
            model_name='acountlesstransactionpointer',
            name='publication_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acountless_transaction_pointers', to='publications.publicationitem'),
        ),
        migrations.AddField(
            model_name='transactionpointer',
            name='publication_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_pointers', to='publications.publicationitem'),
        ),
    ]
