# Generated by Django 3.2.3 on 2022-11-24 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20221124_0108'),
        ('transactions', '0013_auto_20221124_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acountlesstransactionpointer',
            name='publication_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acountless_transaction_pointers', to='publications.publicationitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionpointer',
            name='publication_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_pointers', to='publications.publicationitem'),
            preserve_default=False,
        ),
    ]
