# Generated by Django 3.2.3 on 2022-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20221124_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='acountlesstransaction',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
