# Generated by Django 3.2.3 on 2022-09-29 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('size', models.TextField()),
                ('color', models.TextField()),
                ('sku', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='user_profiles.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShoppingCartPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_cart', to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_assigned', to='publications.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='publications.item')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='publications.item'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('seller', 'item')},
        ),
    ]
