# Generated by Django 3.2.3 on 2022-10-11 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20221004_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
