# Generated by Django 3.2.3 on 2022-10-19 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0004_auto_20221011_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcartpointer',
            name='cart_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingcartpointer',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_itemsº', to='publications.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartpointer',
            unique_together={('cart_owner', 'publication')},
        ),
    ]
