# Generated by Django 3.2.3 on 2022-11-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20221019_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartpointer',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='publications.publication'),
        ),
    ]
