# Generated by Django 3.2.3 on 2022-11-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_alter_shoppingcartpointer_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='photo',
        ),
        migrations.CreateModel(
            name='PublicationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uri', models.TextField()),
                ('publication', models.ManyToManyField(related_name='photos', to='publications.Publication')),
            ],
        ),
    ]
