# Generated by Django 3.2.3 on 2022-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20221110_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationphoto',
            name='image_hash',
            field=models.CharField(default='ImageHash', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
