# Generated by Django 3.2.3 on 2022-11-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publicationphoto_image_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationphoto',
            old_name='publication',
            new_name='publications',
        ),
    ]
