# Generated by Django 3.2.3 on 2022-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_rename_publication_publicationphoto_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CategoryPointer',
        ),
    ]
