# Generated by Django 3.2.3 on 2022-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20221121_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52')], max_length=8),
        ),
    ]
