# Generated by Django 3.2.3 on 2022-11-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='item',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='reserved',
        ),
        migrations.CreateModel(
            name='PublicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_items', to='publications.item')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_items', to='publications.publication')),
            ],
            options={
                'unique_together': {('item', 'publication')},
            },
        ),
    ]
