# Generated by Django 3.2.3 on 2022-11-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0015_auto_20221124_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartpointer',
            name='publication_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='publications.publicationitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartpointer',
            unique_together={('cart_owner', 'publication_item')},
        ),
        migrations.RemoveField(
            model_name='shoppingcartpointer',
            name='publication',
        ),
    ]
