# Generated by Django 3.2.3 on 2022-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_categoryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryPhoto',
        ),
    ]
