# Generated by Django 3.2.3 on 2022-12-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_alter_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationphoto',
            name='image_hash',
        ),
        migrations.RemoveField(
            model_name='publicationphoto',
            name='publications',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publicationphoto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publicationphoto',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='publications.publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicationphoto',
            name='image_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
