# Generated by Django 3.2.3 on 2022-12-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_auto_20221203_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationphoto',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='publications.publication'),
        ),
    ]
