# Generated by Django 3.2.3 on 2022-11-17 00:19

from django.db import migrations


def create_coupon_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    coupon_type = ContentType.objects.get_for_model(
        apps.get_model('transactions', 'Coupon')
    )
    # Create
    create_coupon_permission = Permission.objects.create(
        codename='can_create',
        name='Can create coupon',
        content_type=coupon_type
    )

    Group.objects.get(name='Admin').permissions.add(
        create_coupon_permission,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_transaction_permissions'),
        ('transactions', '0007_coupon')
    ]

    operations = [
        migrations.RunPython(create_coupon_permission),
    ]
