# Generated by Django 3.2.3 on 2022-11-17 23:24

from django.db import migrations


def rename_user_profile_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    user_profile_type = ContentType.objects.get_for_model(
        apps.get_model('user_profiles', 'UserProfile')
    )
    see_users_permissions_query = Permission.objects.filter(
        codename='obtain_all',
        content_type=user_profile_type
    )
    if see_users_permissions_query.exists():
        see_users_permissions = see_users_permissions_query.get()
        see_users_permissions.codename = 'can_get_all_user_profiles'
        see_users_permissions.save()


def rename_coupon_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    coupon_type = ContentType.objects.get_for_model(
        apps.get_model('transactions', 'Coupon')
    )
    coupon_query = Permission.objects.filter(
        codename='can_create',
        content_type=coupon_type
    )
    if coupon_query.exists():
        see_users_permissions = coupon_query.get()
        see_users_permissions.codename = 'can_manage_coupon'
        see_users_permissions.save()


def remove_transactions_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    transaction_type = ContentType.objects.get_for_model(
        apps.get_model('transactions', 'Transaction')
    )
    transaction_permission_query = Permission.objects.filter(
        codename__in=['can_create', 'can_read', 'can_confirm'],
        content_type=transaction_type
    )
    for perm in transaction_permission_query:
        perm.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_add_see_users__permission'),
    ]

    operations = [
        migrations.RunPython(rename_user_profile_permissions),
        migrations.RunPython(rename_coupon_permissions),
        migrations.RunPython(remove_transactions_permissions)
    ]
