# Generated by Django 3.2.3 on 2022-11-23 01:55

from django.db import migrations


def add_delete_user_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    user_profile_type = ContentType.objects.get_for_model(
        apps.get_model('user_profiles', 'UserProfile')
    )
    # Delete user
    delete_user_permission = Permission.objects.create(
        codename='can_delete_user',
        name='Can delete user',
        content_type=user_profile_type
    )
    # Assign permission to group
    Group.objects.get(name='Admin').permissions.add(
        delete_user_permission
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_fix_permissions_naming'),
    ]

    operations = [
        migrations.RunPython(add_delete_user_permissions)
    ]
